#!/bin/sh

# Sourcing layouts for river
source ~/.config/river/layout

# The namespace of the layout client
NAMESPACE=kile

# Selecting the appropriate layout
case $1 in
  stack)
    LAYOUT=$STACK 
    ;;
  rstack)
    LAYOUT=$RSTACK 
    ;;
  dwindle)
    LAYOUT=$DWINDLE 
    ;;
  horizontal)
    LAYOUT=$HORIZONTAL 
    ;;
  group)
    LAYOUT=$GROUP 
    ;;
esac

riverctl set-layout-value "$NAMESPACE" string focused "$LAYOUT"
