#!/usr/bin/env sh

pamixer --toggle-mute

MUTED=$(~/.local/bin/eww state | grep muted | awk '{print $2}')

if $MUTED; then
  ~/.local/bin/eww update muted=false
else
  ~/.local/bin/eww update muted=true
fi

~/.config/eww/scripts/volume $(pamixer --get-volume)
