#!/usr/bin/env sh

status=$(~/.local/bin/eww windows | grep volume)

show() {
  killall -q sleep 2> /dev/null
  if [[ ! $status =~ \* ]]; then
    ~/.local/bin/eww open volume-indicator
  fi
  hide &
}

hide() {
  sleep 1.5 && ~/.local/bin/eww close volume-indicator
}

show

# if [[ -n $1 ]]; then
#   volume=$(echo $1 | awk '{print ($0-int($0)<0.499)?int($0):int($0)+1}')
#   pamixer --set-volume $volume
#   echo $volume >> /tmp/ewwpipe
#   show
# else
#   pamixer --get-volume >> /tmp/ewwpipe
# fi
