#!/bin/sh

inline () {
  echo $@ | tr -d '\r\n'
}

CLIENT=kile
LAYOUT=$(inline "{
  vertical:
  (
    {horizontal: full,ver};
    1;0.65;0
  ),
  horizontal
}|1||0")

riverctl set-layout-value $CLIENT string focused "$LAYOUT"
