#!/bin/sh

inline () {
  echo $@ | tr -d '\r\n' | sed 's/ //g'
}

CLIENT=kile
LAYOUT=$(inline "focused|
  {vertical:
    (
      {horizontal:full,ver};
      1;0.65;0
    ),
    d1
}|||0")

riverctl set-layout-value $CLIENT string layout "$LAYOUT"
