#!/bin/sh

inline () {
  echo $@ | tr -d '\r\n'
}

CLIENT=kile
LAYOUT=$(inline "{
  vertical:
  (d1;1;0.6),
  (
    {horizontal: full, deck};
    1;0.65;0
  )
}|||1")

riverctl set-layout-value $CLIENT string focused "$LAYOUT"
